---
title: "linear_models"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```

fit the first model
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)

fit
summary(fit)

fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "borough", "Borough:")) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 2)
```


## change reference category
```{r}
fit = nyc_airbnb %>% 
  mutate(borough = fct_infreq(borough)) %>% 
  lm(price ~ stars + borough, data = .)

fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "borough", "Borough:")) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 2)

fit %>% 
  broom::glance()
```


## Diagnostics 

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) +
  geom_point()


nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = borough, y = resid)) +
  geom_violin() +
  ylim(-250, 250)
```


## Hypothesis testing
one coefficient - stars

```{r}
fit %>% 
  broom::tidy()

fit_null = lm(price ~ stars, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough, data = nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()

```

## Room type by borough

Interaction...?

```{r}
fit = nyc_airbnb %>% 
  lm(price ~ stars + borough * room_type, data = .)

fit %>% 
  broom::tidy()
```

so... can we fit models by borough?


```{r}
nest_lm_res =
  nyc_airbnb %>% 
  nest(df = -borough) %>% 
  mutate(
    models = map(.x = df, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(-df, -models) %>% 
  unnest(results)
```




